# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calender_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 330)
        Dialog.setMinimumSize(QtCore.QSize(500, 330))
        Dialog.setMaximumSize(QtCore.QSize(500, 330))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(
            79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.SaveButton = QtWidgets.QPushButton(Dialog)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Birthday "))
        self.SaveButton.setText(_translate("Dialog", "save"))


class CalenderDialog(QtWidgets.QDialog):
    def __init__(self):
        super(CalenderDialog, self).__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        self.date = None

        self.ui.SaveButton.clicked.connect(self.save_button_clicked)

    def save_button_clicked(self):
        self.date = self.ui.calendarWidget.selectedDate().toString("yyyy-MM-dd")
        self.done(QtWidgets.QDialog.Accepted)
